import './js/header';
import './js/loader';
import './js/scroll_up';
import './js/BooksApiService';
import './js/onClickDelateBtn';
import './js/all-categories';
import './js/category';
import './js/markup-shopping-list';
import './js/shopping-list';
import './js/support-ukraine';
import './js/modal-book';
import './js/reg-window'
