import './js/header';
import './js/header-current-link';
import './js/dark-theme';
import './js/scroll_up'
import './js/firebase_sandbox';
import './js/firebase';
import './js/loader';;
import './js/BooksApiService';
import './js/all-categories';
import './js/category';
import './js/seeMoreBtn';
import './js/support-ukraine';
import './js/modal-book';
import './js/reg-window';